<?php /* Smarty version 2.6.26, created on 2012-04-11 13:25:45
         compiled from tpl_head:22 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%19^194^194941AA%%tpl_head%3A22.inc'] = '360e5c685810b639b05e7aec04c80b2e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'cms_stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_360e5c685810b639b05e7aec04c80b2e_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('360e5c685810b639b05e7aec04c80b2e','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
