<?php /* Smarty version 2.6.26, created on 2012-04-11 13:20:53
         compiled from listtags.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%1B^1B5^1B53D2DB%%listtags.tpl.inc'] = 'd9383608a0368a6a41a11f655f3ea05f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'lang', 'listtags.tpl', 7, false),array('function', 'cycle', 'listtags.tpl', 29, false),)), $this); ?>
<?php
function _smarty_tplfunc_d9383608a0368a6a41a11f655f3ea05f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d9383608a0368a6a41a11f655f3ea05f','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
