<?php /* Smarty version 2.6.26, created on 2012-04-11 13:45:41
         compiled from siteprefs.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%1B^1B2^1B2DE232%%siteprefs.tpl.inc'] = 'f37ce9b95cab1d87061855d8ad384a31';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'html_options', 'siteprefs.tpl', 26, false),array('modifier', 'lang', 'siteprefs.tpl', 83, false),)), $this); ?>
<?php
function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['languages'],'selected' => $_smarty->_tpl_vars['frontendlang']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','1');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['wysiwyg'],'selected' => $_smarty->_tpl_vars['frontendwysiwyg']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','2');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['themes'],'selected' => $_smarty->_tpl_vars['logintheme']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','3');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['search_modules'],'selected' => $_smarty->_tpl_vars['search_module']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','4');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['titlemenu'],'selected' => $_smarty->_tpl_vars['listcontent_showtitle']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','5');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showalias']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','6');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showurl']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','7');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_urls']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','8');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_flaturls']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','9');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_mandatory_urls']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','10');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_contenttypes'],'selected' => $_smarty->_tpl_vars['disallowed_contenttypes']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','11');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_attributes'],'selected' => $_smarty->_tpl_vars['basic_attributes']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','12');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['pseudocron_options'],'selected' => $_smarty->_tpl_vars['pseudocron_granularity']), $_smarty);
}


function _smarty_tplfunc_f37ce9b95cab1d87061855d8ad384a31_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f37ce9b95cab1d87061855d8ad384a31','13');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['adminlog_options'],'selected' => $_smarty->_tpl_vars['adminlog_lifetime']), $_smarty);
}



?>
