<?php /* Smarty version 2.6.26, created on 2012-04-11 13:25:45
         compiled from tpl_top:22 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = 'e8e0dbaca862e9f13b7c8043db5a8362';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_e8e0dbaca862e9f13b7c8043db5a8362_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e8e0dbaca862e9f13b7c8043db5a8362','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
