<?php /* Smarty version 2.6.26, created on 2012-04-11 13:48:39
         compiled from listcssassoc.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%64^64F^64FC46BF%%listcssassoc.tpl.inc'] = 'a879ab580bc0d0bc944ab86badfe9ddd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'listcssassoc.tpl', 19, false),)), $this); ?>
<?php
function _smarty_tplfunc_a879ab580bc0d0bc944ab86badfe9ddd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a879ab580bc0d0bc944ab86badfe9ddd','0');echo smarty_function_cycle(array('values' => 'row1,row2','assign' => 'currow'), $_smarty);
}



?>
