<?php /* Smarty version 2.6.26, created on 2012-04-11 13:19:31
         compiled from tpl_head:25 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%87^872^872DD409%%tpl_head%3A25.inc'] = 'af70ffa81c0a23ba4bcd5cc135eab88b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:25', 2, false),array('function', 'title', 'tpl_head:25', 2, false),array('function', 'metadata', 'tpl_head:25', 3, false),array('function', 'cms_stylesheet', 'tpl_head:25', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_af70ffa81c0a23ba4bcd5cc135eab88b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('af70ffa81c0a23ba4bcd5cc135eab88b','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_af70ffa81c0a23ba4bcd5cc135eab88b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('af70ffa81c0a23ba4bcd5cc135eab88b','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_af70ffa81c0a23ba4bcd5cc135eab88b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('af70ffa81c0a23ba4bcd5cc135eab88b','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_af70ffa81c0a23ba4bcd5cc135eab88b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('af70ffa81c0a23ba4bcd5cc135eab88b','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}



?>
