<?php /* Smarty version 2.6.26, created on 2012-04-11 13:16:08
         compiled from tpl_body:24 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%9F^9F5^9F529885%%tpl_body%3A24.inc'] = 'edd4077eccd88f97ffcfb0eaa38a23ea';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'root_url', 'tpl_body:24', 7, false),array('function', 'sitename', 'tpl_body:24', 7, false),array('function', 'menu', 'tpl_body:24', 15, false),array('function', 'title', 'tpl_body:24', 25, false),array('function', 'content', 'tpl_body:24', 27, false),array('function', 'cms_module', 'tpl_body:24', 37, false),array('function', 'current_date', 'tpl_body:24', 58, false),)), $this); ?>
<?php
function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','0');echo smarty_function_root_url(array(), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','2');echo smarty_cms_function_menu(array('template' => "Mobility : minimal_menu",'number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','3');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','4');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','5');echo smarty_cms_function_cms_module(array('module' => 'Search'), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','6');echo smarty_cms_function_menu(array('template' => "Mobility : minimal_menu",'start_level' => '1','collapse' => '1'), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','7');echo smarty_cms_function_cms_module(array('module' => 'News'), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','8');echo smarty_cms_function_current_date(array('format' => "%Y"), $_smarty);
}


function _smarty_tplfunc_edd4077eccd88f97ffcfb0eaa38a23ea_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edd4077eccd88f97ffcfb0eaa38a23ea','9');echo smarty_cms_function_sitename(array(), $_smarty);
}



?>
