<?php /* Smarty version 2.6.26, created on 2012-04-11 13:16:08
         compiled from tpl_top:24 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%BB^BB8^BB846DBE%%tpl_top%3A24.inc'] = '244fd818fbf9901ad11e82218c69eb32';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:24', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_244fd818fbf9901ad11e82218c69eb32_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('244fd818fbf9901ad11e82218c69eb32','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
