<?php /* Smarty version 2.6.26, created on 2012-04-11 13:19:30
         compiled from tpl_top:25 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%CC^CC8^CC835D28%%tpl_top%3A25.inc'] = 'f26cf49bdb0a830043f33f94a9dd4f20';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:25', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_f26cf49bdb0a830043f33f94a9dd4f20_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f26cf49bdb0a830043f33f94a9dd4f20','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
