<?php /* Smarty version 2.6.26, created on 2012-04-11 13:19:30
         compiled from tpl_body:25 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%E8^E85^E855A813%%tpl_body%3A25.inc'] = 'cdf656a012bf28e6541b1425eb511a4a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_body:25', 6, false),array('function', 'search', 'tpl_body:25', 10, false),array('function', 'menu', 'tpl_body:25', 15, false),array('function', 'title', 'tpl_body:25', 23, false),array('function', 'print', 'tpl_body:25', 25, false),array('function', 'content', 'tpl_body:25', 28, false),)), $this); ?>
<?php
function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','1');echo smarty_cms_function_search(array(), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','2');echo smarty_cms_function_menu(array('template' => "zionnarrows : minimal_menu",'number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','3');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','4');echo smarty_cms_function_print(array(), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','5');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_cdf656a012bf28e6541b1425eb511a4a_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cdf656a012bf28e6541b1425eb511a4a','6');echo smarty_cms_function_menu(array('template' => "zionnarrows : minimal_menu",'start_level' => '1','collapse' => '1'), $_smarty);
}



?>
