<?php /* Smarty version 2.6.26, created on 2012-04-11 13:16:08
         compiled from tpl_head:24 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\%%F0^F02^F02AE49F%%tpl_head%3A24.inc'] = 'f7b94676362c7f26b7e1d3b1eb28185e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'metadata', 'tpl_head:24', 2, false),array('function', 'cms_stylesheet', 'tpl_head:24', 3, false),array('function', 'sitename', 'tpl_head:24', 4, false),array('function', 'title', 'tpl_head:24', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_f7b94676362c7f26b7e1d3b1eb28185e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b94676362c7f26b7e1d3b1eb28185e','0');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f7b94676362c7f26b7e1d3b1eb28185e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b94676362c7f26b7e1d3b1eb28185e','1');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f7b94676362c7f26b7e1d3b1eb28185e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b94676362c7f26b7e1d3b1eb28185e','2');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_f7b94676362c7f26b7e1d3b1eb28185e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b94676362c7f26b7e1d3b1eb28185e','3');echo smarty_cms_function_title(array(), $_smarty);
}



?>
