<?php /* Smarty version 2.6.26, created on 2012-04-11 07:40:16
         compiled from content:content_en */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\75^%%70^707^707A8977%%content%3Acontent_en.inc'] = '2f07e145ccd746ddadb056351152c77a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'FormBuilder', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2f07e145ccd746ddadb056351152c77a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2f07e145ccd746ddadb056351152c77a','0');echo $_smarty->_plugins['function']['FormBuilder'][0][0]->function_plugin(array('form' => 'order'), $_smarty);
}



?>
