<?php /* Smarty version 2.6.26, created on 2012-04-11 08:12:21
         compiled from content:content_en */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\77^%%70^707^707A8977%%content%3Acontent_en.inc'] = '07e9a93d986471c90baffbf5eadb66b9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'FormBuilder', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_07e9a93d986471c90baffbf5eadb66b9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('07e9a93d986471c90baffbf5eadb66b9','0');echo $_smarty->_plugins['function']['FormBuilder'][0][0]->function_plugin(array('form' => 'Availability'), $_smarty);
}



?>
