<?php /* Smarty version 2.6.26, created on 2012-04-11 08:30:19
         compiled from content:content_en */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\78^%%70^707^707A8977%%content%3Acontent_en.inc'] = '1aa95453f6b9ca0f4155287d55587153';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'FormBuilder', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_1aa95453f6b9ca0f4155287d55587153_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1aa95453f6b9ca0f4155287d55587153','0');echo $_smarty->_plugins['function']['FormBuilder'][0][0]->function_plugin(array('form' => 'Resource_Booking'), $_smarty);
}



?>
