<?php /* Smarty version 2.6.26, created on 2012-04-11 08:07:35
         compiled from content:content_en */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\__CMS_PREVIEW_PAGE__^%%70^707^707A8977%%content%3Acontent_en.inc'] = '75856245365b358ce079996aa4e7552f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'FormBuilder', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_75856245365b358ce079996aa4e7552f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('75856245365b358ce079996aa4e7552f','0');echo $_smarty->_plugins['function']['FormBuilder'][0][0]->function_plugin(array('form' => 'Availability'), $_smarty);
}



?>
