<?php /* Smarty version 2.6.26, created on 2012-04-11 08:07:35
         compiled from module_db_tpl:FormBuilder%3Bfb_6 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBuilder^%%FF^FFF^FFF1E9A7%%module_db_tpl%3AFormBuilder%3Bfb_6.inc'] = 'fdd43a255ca784704022f8e0584b6067';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'eval', 'module_db_tpl:FormBuilder;fb_6', 87, false),)), $this); ?>
<?php
function _smarty_tplfunc_fdd43a255ca784704022f8e0584b6067_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fdd43a255ca784704022f8e0584b6067','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->input), $_smarty);
}



?>
