<?php /* Smarty version 2.6.26, created on 2012-04-11 10:26:17
         compiled from module_db_tpl:FormBuilder%3Bfb_4 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBuilder^%%11^11F^11FF888B%%module_db_tpl%3AFormBuilder%3Bfb_4.inc'] = '564732beef6ce0540a63b0ee77987024';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'eval', 'module_db_tpl:FormBuilder;fb_4', 87, false),)), $this); ?>
<?php
function _smarty_tplfunc_564732beef6ce0540a63b0ee77987024_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('564732beef6ce0540a63b0ee77987024','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->input), $_smarty);
}



?>
