<?php /* Smarty version 2.6.26, created on 2012-04-11 07:40:17
         compiled from module_db_tpl:FormBuilder%3Bfb_5 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBuilder^%%66^66F^66F8B81D%%module_db_tpl%3AFormBuilder%3Bfb_5.inc'] = '5cc0a1428f21fda6be408d5ac8cb2634';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'eval', 'module_db_tpl:FormBuilder;fb_5', 87, false),)), $this); ?>
<?php
function _smarty_tplfunc_5cc0a1428f21fda6be408d5ac8cb2634_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5cc0a1428f21fda6be408d5ac8cb2634','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->input), $_smarty);
}



?>
