<?php /* Smarty version 2.6.26, created on 2012-04-11 08:08:18
         compiled from module_db_tpl:FormBuilder%3Bfb_7 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBuilder^%%88^88F^88F6D931%%module_db_tpl%3AFormBuilder%3Bfb_7.inc'] = 'a61b38574301ca221864935e9f4bad4d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'eval', 'module_db_tpl:FormBuilder;fb_7', 87, false),)), $this); ?>
<?php
function _smarty_tplfunc_a61b38574301ca221864935e9f4bad4d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a61b38574301ca221864935e9f4bad4d','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->input), $_smarty);
}



?>
