<?php /* Smarty version 2.6.26, created on 2012-04-11 08:30:19
         compiled from module_db_tpl:FormBuilder%3Bfb_9 */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBuilder^%%6F^6F4^6F4EF436%%module_db_tpl%3AFormBuilder%3Bfb_9.inc'] = '9c4fd935e673fc75f425453fc262f5cf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'eval', 'module_db_tpl:FormBuilder;fb_9', 87, false),)), $this); ?>
<?php
function _smarty_tplfunc_9c4fd935e673fc75f425453fc262f5cf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9c4fd935e673fc75f425453fc262f5cf','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->input), $_smarty);
}



?>
