<?php /* Smarty version 2.6.26, created on 2012-04-11 06:16:47
         compiled from module_file_tpl:FormBrowser%3Badminpanel.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\FormBrowser^%%6C^6C7^6C74F9A5%%module_file_tpl%3AFormBrowser%3Badminpanel.tpl.inc'] = '1d0c4996db2577591aee2e7af4d5b16e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:FormBrowser;adminpanel.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_1d0c4996db2577591aee2e7af4d5b16e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d0c4996db2577591aee2e7af4d5b16e','0');echo smarty_function_cycle(array('values' => 'row1,row2','assign' => 'rowclass'), $_smarty);
}



?>
