<?php /* Smarty version 2.6.26, created on 2012-04-11 13:45:42
         compiled from module_file_tpl:MicroTiny%3Bmicrotinyconfig.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\MicroTiny^%%A4^A4D^A4D98377%%module_file_tpl%3AMicroTiny%3Bmicrotinyconfig.tpl.inc'] = 'eb8706631f58863c45c61b89cb1379ba';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_stylesheet', 'module_file_tpl:MicroTiny;microtinyconfig.tpl', 8, false),)), $this); ?>
<?php
function _smarty_tplfunc_eb8706631f58863c45c61b89cb1379ba_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb8706631f58863c45c61b89cb1379ba','0');echo smarty_cms_function_cms_stylesheet(array('templateid' => $_smarty->_tpl_vars['templateid'],'nolinks' => 1,'adjustforeditor' => 1), $_smarty);
}


function _smarty_tplfunc_eb8706631f58863c45c61b89cb1379ba_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb8706631f58863c45c61b89cb1379ba','1');echo smarty_cms_function_cms_stylesheet(array('templateid' => $_smarty->_tpl_vars['templateid'],'nolinks' => 1), $_smarty);
}



?>
