<?php /* Smarty version 2.6.26, created on 2012-04-11 13:29:15
         compiled from module_file_tpl:ModuleManager%3Badmin_search_tab.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\ModuleManager^%%AF^AF0^AF0F61D7%%module_file_tpl%3AModuleManager%3Badmin_search_tab.tpl.inc'] = 'af7659d1b3e585f598c45194292bec9e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:ModuleManager;admin_search_tab.tpl', 63, false),)), $this); ?>
<?php
function _smarty_tplfunc_af7659d1b3e585f598c45194292bec9e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('af7659d1b3e585f598c45194292bec9e','0');echo smarty_function_cycle(array('values' => 'row1,row2','assign' => 'rowclass'), $_smarty);
}



?>
