<?php /* Smarty version 2.6.26, created on 2012-04-11 13:32:24
         compiled from module_file_tpl:News%3Bcustomfieldstab.tpl */

$this->_cache_serials['D:\wamp\www\cms\tmp\templates_c\News^%%DC^DCB^DCB07EC3%%module_file_tpl%3ANews%3Bcustomfieldstab.tpl.inc'] = 'd7b34abc71e10f6dd9c2a34c2a1b042f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:News;customfieldstab.tpl', 36, false),)), $this); ?>
<?php
function _smarty_tplfunc_d7b34abc71e10f6dd9c2a34c2a1b042f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d7b34abc71e10f6dd9c2a34c2a1b042f','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
